tasks:
  sync-locks:
    triggers:
    - "pixi.toml"
    - "pixi.lock"
    stage:
    - "pixi.lock"
    - "envs/"

  generate-config:
    triggers:
    - "scripts/lib/validation/config/**"
    stage:
    - "config/"
    - "doc/"
    - "*.yaml"
    - "*.yml"

app:
  trusted_users:
  - daniel-rdt
  runs:
  - name: "config.validator.yaml"
    configfile: "config/test/config.validator.yaml"
    triggers: [main, pr]
    cache:
      key: "validator-{YYYY}-{MM}"
      dirs: ["data"]
    import_networks:
    - "results/validation/networks/base_s_50___2050.nc"
