# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 2

python:
  version: 3.8
  install:
  - requirements: doc/requirements.txt
  system_packages: true
