# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
  - graphviz

python:
  install:
  - requirements: doc/requirements.txt
