# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 2

python:
  version: 3.7
  install:
    - requirements: doc/requirements.txt
  system_packages: true

# conda:
#     environment: envs/environment.docs.yaml
