# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC-BY-4.0

site_name: PyPSA-Eur
site_url: https://pypsa-eur.readthedocs.io
repo_url: https://github.com/pypsa/pypsa-eur
repo_name: pypsa/pypsa-eur

docs_dir: doc

theme:
  name: material
  logo: img/logo.svg
  features:
  - navigation.sections
  - navigation.expand
  - search.suggest
  - content.code.copy
  - content.tabs.link

nav:
- Home: index.md
- Getting Started:
  - Introduction: introduction.md
  - Installation: installation.md
  - "Tutorial: Electricity-Only": tutorial.md
  - "Tutorial: Sector-Coupled": tutorial_sector.md
- Configuration:
  - Wildcards: wildcards.md
  - Configuration: configuration.md
  - Foresight Options: foresight.md
  - Techno-Economic Assumptions: costs.md
- Rules Overview:
  - Retrieving Data: retrieve.md
  - Building Electricity Networks: preparation.md
  - Building Sector-Coupled Networks: sector.md
  - Solving Networks: solving.md
  - OETC Integration: oetc.md
  - Plotting and Summaries: plotting.md
- Implementation details for sector-coupled systems:
  - Spatial resolution: spatial_resolution.md
  - Supply and demand: supply_demand.md
- References:
  - Release Notes: release_notes.md
  - Licenses: licenses.md
  - Data Sources:
    - data_sources.md
    - Base Network: data-base-network.md
    - Cutouts: data-cutouts.md
    - Data Repositories: data-repos.md
  - Validation: validation.md
  - Limitations: limitations.md
  - Contributing:
    - contributing.md
    - Validation Development: validation_dev.md
  - Support: support.md
  - Publications: publications.md

plugins:
- search
- autorefs
- macros:
    module_name: doc/macros
    j2_comment_start_string: "{%#"
    j2_comment_end_string: "#%}"
- table-reader
- mkdocstrings:
    default_handler: python
    enable_inventory: true
    handlers:
      python:
        paths: [scripts, .]
        options:
          docstring_style: numpy
          show_source: false
          show_root_heading: false
          show_root_full_path: false
          members: false
          allow_inspection: true
        inventories:
        - https://docs.python.org/3/objects.inv
- bibtex:
    bib_file: doc/publications.bib
    enable_inline_citations: false

markdown_extensions:
- footnotes
- admonition
- pymdownx.details
- pymdownx.snippets:
    base_path: .
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.arithmatex:
    generic: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight
- pymdownx.inlinehilite
- tables
- attr_list
- md_in_html
- toc:
    permalink: true

hooks:
- doc/hooks.py

extra_javascript:
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
