
th_24c24:
  clustering:
    temporal:
      resolution_elec: 24c24

th_48c24:
  clustering:
    temporal:
      resolution_elec: 48c24

th_168c24:
  clustering:
    temporal:
      resolution_elec: 168c24

th_8760:
  clustering:
    temporal:
      resolution_elec: 1H
