
lin_24c24:
  clustering:
    temporal:
      resolution_elec: 24c24

uc_24c24:
  clustering:
    temporal:
      resolution_elec: 24c24
  conventional:
    unit_commitment: true

  solving:
    options:
      load_shedding: 
        enable: true
      skip_iterations: true
      transmission_losses: 0
      linearized_unit_commitment: false
      noisy_costs: false
    solver:
      name: [gurobi, smspp, smspp]
      options: [gurobi-default, smspp-ucblock, smspp-investmentblock]
    solver_options:
      smspp-ucblock:
        capacity_expansion_ucblock: true
        enable_thermal_units: true
        configfile: "UCBlock/uc_solverconfig_grb.txt"
      smspp-investmentblock:
        capacity_expansion_ucblock: false
        enable_thermal_units: true
    runtime: 12H

lin_48c24:
  clustering:
    temporal:
      resolution_elec: 48c24

uc_48c24:
  clustering:
    temporal:
      resolution_elec: 48c24
  conventional:
    unit_commitment: true

  solving:
    options:
      load_shedding: 
        enable: true
      skip_iterations: true
      transmission_losses: 0
      linearized_unit_commitment: false
      noisy_costs: false
    solver:
      name: [gurobi, smspp, smspp]
      options: [gurobi-default, smspp-ucblock, smspp-investmentblock]
    solver_options:
      smspp-ucblock:
        capacity_expansion_ucblock: true
        enable_thermal_units: true
        configfile: "UCBlock/uc_solverconfig_grb.txt"
      smspp-investmentblock:
        capacity_expansion_ucblock: false
        enable_thermal_units: true
    runtime: 12H

lin_168c24:
  clustering:
    temporal:
      resolution_elec: 168c24

uc_168c24:
  clustering:
    temporal:
      resolution_elec: 168c24
  conventional:
    unit_commitment: true

  solving:
    options:
      load_shedding: 
        enable: true
      skip_iterations: true
      transmission_losses: 0
      linearized_unit_commitment: false
      noisy_costs: false
    solver:
      name: [gurobi, smspp, smspp]
      options: [gurobi-default, smspp-ucblock, smspp-investmentblock]
    solver_options:
      smspp-ucblock:
        capacity_expansion_ucblock: true
        enable_thermal_units: true
        configfile: "UCBlock/uc_solverconfig_grb.txt"
      smspp-investmentblock:
        capacity_expansion_ucblock: false
        enable_thermal_units: true
    runtime: 12H

lin_8760:
  clustering:
    temporal:
      resolution_elec: 1H

uc_8760:
  clustering:
    temporal:
      resolution_elec: 1H
  conventional:
    unit_commitment: true

  solving:
    options:
      load_shedding: 
        enable: true
      skip_iterations: true
      transmission_losses: 0
      linearized_unit_commitment: false
      noisy_costs: false
    solver:
      name: [gurobi, smspp, smspp]
      options: [gurobi-default, smspp-ucblock, smspp-investmentblock]
    solver_options:
      smspp-ucblock:
        capacity_expansion_ucblock: true
        enable_thermal_units: true
        configfile: "UCBlock/uc_solverconfig_grb.txt"
      smspp-investmentblock:
        capacity_expansion_ucblock: false
        enable_thermal_units: true
    runtime: 12H
