# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

name: pypsa-eur
channels:
- conda-forge
- bioconda
dependencies:
- python>=3.8
- pip

- linopy



- pip:
  - tsam>=2.3.1
  - snakemake-storage-plugin-http
  - snakemake-executor-plugin-slurm
  - snakemake-executor-plugin-cluster-generic
  - highspy
