# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

baseline_eu_dem:
  co2_budget_apply: false
  sector:
    endo_industry:
      regional_steel_demand: false
#    co2_sequestration_potential:
#      2030: 50
#      2040: 200
#      2050: 350
    ammonia: true

climate_policy_eu_dem:
  co2_budget_apply: true
  sector:
    endo_industry:
      regional_steel_demand: false
    ammonia: true

baseline_regional_dem:
  co2_budget_apply: false
  sector:
    endo_industry:
      regional_steel_demand: true
    ammonia: regional
    

climate_policy_regional_dem:
  co2_budget_apply: true
  sector:
    endo_industry:
      regional_steel_demand: true
    ammonia: regional
#    co2_sequestration_potential:
#      2030: 50
#      2040: 200
#      2050: 300
