# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

# Climate policy: NO, Relocation: NO, Industrial policy: REGAIN

import_base_reg_regain_import:
  co2_budget:
    2020: 10
    2030: 10
    2040: 10
    2050: 10
  weather_years:
    enable: true
    rcp: 4-5
  sector:
    endo_industry:
      regional_steel_demand: true
      dri_import: true
      regional_cement_demand: true
      regional_hvc: true
      policy_scenario: regain
    methanol:
      regional_methanol_demand: true
    ammonia: regional
  imports:
    enable: true
    price:
      methanol_adb: 137.65 #€/MWh methanol average
      ammonia_adb: 116.65 #€/MWh ammonia average

# Climate policy: YES, Relocation: NO, Industrial policy: REGAIN
import_policy_reg_regain:
  co2_budget:
    2020: 1
    2030: 0.450 # 55% reduction by 2030 (Ff55)
    2040: 0.100 # 90% by 2040
    2050: 0.000 # climate-neutral by 2050
  weather_years:
    enable: true
    rcp: 4-5
  sector:
    endo_industry:
      regional_steel_demand: true
      dri_import: true
      regional_cement_demand: true
      regional_hvc: true
      policy_scenario: regain
    methanol:
      regional_methanol_demand: true
    ammonia: regional
  imports:
    enable: true
    price:
      methanol_adb: 137.65 #€/MWh methanol average
      ammonia_adb: 116.65 #€/MWh ammonia average

# Climate policy: NO, Relocation: NO, Industrial policy: DEINDUSTRIAL
import_base_reg_deindustrial:
  co2_budget:
    2020: 10
    2030: 10
    2040: 10
    2050: 10
  weather_years:
    enable: true
    rcp: 4-5
  sector:
    endo_industry:
      regional_steel_demand: true
      dri_import: true
      regional_cement_demand: true
      regional_hvc: true
      policy_scenario: deindustrial
    methanol:
      regional_methanol_demand: true
    ammonia: regional
  imports:
    enable: true
    price:
      methanol_adb: 137.65 #€/MWh methanol average
      ammonia_adb: 116.65 #€/MWh ammonia average

# Climate policy: YES, Relocation: NO, Industrial policy: DEINDUSTRIAL
import_policy_reg_deindustrial:
  co2_budget:
    2020: 1
    2030: 0.450 # 55% reduction by 2030 (Ff55)
    2040: 0.100 # 90% by 2040
    2050: 0.000 # climate-neutral by 2050
  weather_years:
    enable: true
    rcp: 4-5
  sector:
    endo_industry:
      regional_steel_demand: true
      dri_import: true
      regional_cement_demand: true
      regional_hvc: true
      policy_scenario: deindustrial
    methanol:
      regional_methanol_demand: true
    ammonia: regional
    imports:
      enable: true
      price:
        methanol_adb: 137.65 #€/MWh methanol average
        ammonia_adb: 116.65 #€/MWh ammonia average
