# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: ""
  name: 
  - policy_eu_dem
  scenarios:
    enable: true
    file: config/industry_scenarios.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  simpl:
  - ''
  ll:
  - vopt
  clusters:
  - 39
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  # - 2020
  - 2030
  - 2040
  - 2050

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  retrieve_databundle: true
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: true
  custom_busmap: false
  drop_leap_day: true

co2_budget_apply: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#electricity
electricity:
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT]
    StorageUnit: [] # battery, H2
    Store: [battery, H2]
    Link: [] # H2 pipeline
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, offwind-float, hydro]

# docs
# TODO: PyPSA-Eur merge issue in prepare_sector_network.py
# regulate what components with which carriers are kept from PyPSA-Eur;
# some technologies are removed because they are implemented differently
# (e.g. battery or H2 storage) or have different year-dependent costs
# in PyPSA-Eur-Sec
pypsa_eur:
  Bus:
  - AC
  Link:
  - DC
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - offwind-float
  #- solar-hsat
  - solar
  - ror
  - nuclear
  StorageUnit:
  - PHS
  - hydro
  Store: []

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  transport: true
  heating: true
  biomass: true
  industry: true
  agriculture: true
  fossil_fuels: true
  bev_dsm: false
  v2g: false
  co2_sequestration_potential:
    2020: 0
    2025: 0
    2030: 50
    2035: 100
    2040: 200
    2045: 200
    2050: 200
  min_part_load_fischer_tropsch: 0.3 # 0.5 #ADB
  H2_network: false
  endo_industry:
    enable: true
    regional_steel_demand: false
    cement_prod_growth: true
    endo_chemicals: true
  # This wildcard is not working if only in config.default.yaml (I have no idea why)
  chp:
    enable: true
    fuel:
    - solid biomass # For solid biomass, CHP with and without CC are added
    - gas # For all other fuels the same techno economic data from gas CHP is taken
    micro_chp: false # Only gas is used for micro_chp

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  temporal:
    resolution_elec: false
    resolution_sector: 2920h

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#plotting
plotting:
  tech_colors:
    #ADB
    BF-BOF: 'blue'
    DRI-EAF: 'blue'
    iron: 'green'
    cement: 'grey'
    limestone: 'yellow'
    cement plant: 'grey'
    cement process emissions: 'grey'
    cement process emissions CC: 'green'
    steel process emissions: 'grey'
    steel process emissions CC: 'green'
    steel: 'yellow'
    drigas: 'grey'
