# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

baseline:
  co2_budget:
    2020: 1.0
    2025: 1.0
    2030: 1.0
    2035: 1.0
    2040: 1.0
    2045: 1.0
    2050: 1.0

climate_policy:
  co2_budget:
    2020: 0.701
    2025: 0.524
    2030: 0.297
    2035: 0.150
    2040: 0.071
    2045: 0.032
    2050: 0.000

