# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: ""
  name: #"all"
  - import_policy_reg_deindustrial
  - import_policy_reg_regain
  #- base_reg_deindustrial
  #- base_reg_regain
  #- policy_reg_regain
  #- policy_reg_deindustrial
  #- policy_eu_regain_flex
  #- policy_reg_deindustrial_flex
  #- policy_eu_deindustrial_flex
  #- policy_eu_regain
  #- policy_eu_deindustrial
  #- policy_reg_deindustrial_pf
  - policy_reg_maintain
  scenarios:
    enable: true
    file: config/industry_policy_scenarios_45_maintain.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  simpl:
  - ''
  ll:
  - vopt
  clusters:
  - 39
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  # - 2020
  - 2030
  - 2040
  - 2050

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  retrieve_databundle: true
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: true
  custom_busmap: false
  drop_leap_day: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#co2-budget
co2_budget:
  2020: 1
  2030: 0.450 # 55% reduction by 2030 (Ff55)
  2040: 0.100 # 90% by 2040
  2050: 0.000 # climate-neutral by 2050

weather_years:
  enable: true
  rcp: 4-5
# RCP 2.6 is 2-6, RCP 4.5 is 4-5, RCP 8.5 is 8-5
  global_regional_models: CNRM-CERFACS-CM5--CNRM-ALADIN63
# Global Climate Models (GCMs): CNRM-CERFACS-CM5, MPI-M-MPI-ESM-LR, MIROC-MIROC5
# Regional Climate Models (RCMs): CNRM-ALADIN63, ICTP-RegCM4-6, CLMcom-CLM-CCLM4-8-17
# Global model 1 has to be connected to regional model 1, so e.g. CNRM_CERFACS_CM5__CNRM_ALADIN63 but not CNRM_CERFACS_ICTP-RegCM4-6


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#electricity
electricity:
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT]
    StorageUnit: [] # battery, H2
    Store: [battery, H2]
    Link: [] # H2 pipeline
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, offwind-float, hydro]

existing_capacities:
  threshold_capacity_industry: 0.001

# docs
# TODO: PyPSA-Eur merge issue in prepare_sector_network.py
# regulate what components with which carriers are kept from PyPSA-Eur;
# some technologies are removed because they are implemented differently
# (e.g. battery or H2 storage) or have different year-dependent costs
# in PyPSA-Eur-Sec
pypsa_eur:
  Bus:
  - AC
  Link:
  - DC
  Generator:
  - onwind
  - offwind-ac
  - offwind-dc
  - offwind-float
  #- solar-hsat
  - solar
  - ror
  - nuclear
  StorageUnit:
  - PHS
  - hydro
  Store: []

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  transport: true
  heating: true
  biomass: true
  industry: true
  agriculture: true
  fossil_fuels: true
  bev_dsm: false
  v2g: false
  co2_spatial: false
  co2_network: false
  co2_sequestration_potential:
    2020: 0
    2025: 0
    2030: 50
    2035: 100
    2040: 200
    2045: 200
    2050: 200
  min_part_load_fischer_tropsch: 0.3 # 0.5 #ADB
  H2_network: false
  endo_industry:
    enable: true
    regional_steel_demand: false
    dri_import: false
    regional_cement_demand: false
    empirical_demand_growth: false
    endo_chemicals: true
    endo_ammonia: true # if true it also skips the ammonia cracker for simplicity
    endo_hvc: true # Adding biomass_to_liquid and biomass_to_liquid_cc
    endo_methanol: true
    regional_hvc: false
    policy_scenario: deindustrial
  biomass_to_liquid: true
  biomass_to_liquid_cc: false
  tes: false
  electricity_distribution_grid: false

  # This wildcard is not working if only in config.default.yaml (I have no idea why)
  chp:
    enable: true
    fuel:
    - solid biomass # For solid biomass, CHP with and without CC are added
    - gas # For all other fuels the same techno economic data from gas CHP is taken
    micro_chp: false # Only gas is used for micro_chp
  heat_vent:
    urban central: false
    urban decentral: false
    rural: false
  # No heat integration to not mess up with the rest of the optimization
  use_fischer_tropsch_waste_heat: false
  use_haber_bosch_waste_heat: false
  use_methanolisation_waste_heat: false
  use_methanation_waste_heat: false
  use_fuel_cell_waste_heat: false
  use_electrolysis_waste_heat: false

industry:
  oil_refining_emissions: 0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  temporal:
    resolution_elec: false
    resolution_sector: 3h


# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#plotting
plotting:
  balance_timeseries:
    monthly: false
    annual: false
  tech_colors:
    #ADB
    BF-BOF: 'blue'
    DRI-EAF: 'blue'
    iron: 'green'
    cement: 'grey'
    limestone: 'yellow'
    cement plant: 'grey'
    cement process emissions: 'grey'
    cement process emissions CC: 'green'
    steel process emissions: 'grey'
    steel process emissions CC: 'green'
    steel: 'yellow'
    syn gas for DRI: 'grey'
    HVC: 'yellow'
    naphtha steam cracker: 'grey'

solving:
  solver:
    name: gurobi
    options: gurobi-default

  solver_options:
    gurobi-crossover:
      threads: 8
      method: 2 # barrier
      crossover: 1
      BarConvTol: 1.e-6
      Seed: 123
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200
