# yaml-language-server: $schema=schema.default.json

run:
  prefix: ""
  name: "IT-elec"
  scenarios:
    enable: false
    file: config/scenarios.yaml
  disable_progressbar: true
  shared_resources:
    policy: false
    exclude: []
  use_shadow_directory: false

foresight: overnight

scenario:
  clusters:
  - 2
  # - 5
  # - 10
  # - 20
  # - 50
  opts:
  - ''

countries:
- IT

clustering:
  temporal:
    resolution_elec: 4c24

conventional:
  unit_commitment: true

solving:
  options:
    skip_iterations: true
    transmission_losses: 0
    linearized_unit_commitment: false
    noisy_costs: false
  solver:
    name: [gurobi, smspp, smspp]
    options: [gurobi-default, smspp-ucblock, smspp-ucblock-DP]
  solver_options:
    smspp-ucblock:
      capacity_expansion_ucblock: true
      enable_thermal_units: true
    smspp-ucblock-DP:
      capacity_expansion_ucblock: true
      enable_thermal_units: true
      configfile: "config/smspp/Thermal_DynamicProgramming/TUBSCfg-DP.txt"
      pysmspp_options:
        "B": "config/smspp/Thermal_DynamicProgramming/TUBCfg-DP.txt"
