# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: pypsa-eur-docs
channels:
  - conda-forge
dependencies:
  - python<=3.7
  - pip
  - pypsa>=0.17.1
  - atlite>=0.2.2
  - dask<=2021.3.1 # until https://github.com/dask/dask/issues/7583 is solved
  - pre-commit

  # Dependencies of the workflow itself
  - scikit-learn
  - pycountry
  - seaborn
  - memory_profiler
  - yaml
  - pytables
  - powerplantmatching>=0.4.8

  # GIS dependencies have to come all from conda-forge
  - cartopy
  - descartes

  - pip:
    - vresutils==0.3.1
    - sphinx
    - sphinx_rtd_theme
