name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]    

      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v1
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
    - 
      name: Build Dev Container Image
      uses: devcontainers/ci@v0.2
      with:
        subFolder: .github
        imageName: ghcr.io/${{ github.repository }}
        cacheFrom: ghcr.io/${{ github.repository }}
        push: never  

    - name: Test Container Image
      run: |
        docker run --rm ghcr.io/${{ github.repository }} /bin/bash -c  "bash .github/.devcontainer/test.sh"

    - name: Push Container Image
      if: ${{ success() }}
      run: |
        docker push ghcr.io/${{ github.repository }}