name: Security scan
on:
  push:
    branches: [master]
    paths: [pixi.lock]
  schedule:
  - cron: "0 6 * * *"
jobs:
  security-scan:
    name: SBOM and vulnerability scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v6

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.9.5
      with:
        pixi-version: v0.68.1

    - name: Generate SBOM
      id: sbom
      uses: anchore/sbom-action@v0.24.0
      with:
        path: ".pixi/envs/default"
        output-file: sbom.spdx.json
        dependency-snapshot: true

    - name: Generate SBOM vulnerability report
      id: scan
      uses: anchore/scan-action@v7.4.0
      with:
        sbom: sbom.spdx.json
        fail-build: false
        add-cpes-if-none: true

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v4
      if: always()
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
